// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5fQEMdH-xppVCMzw67IstHvqeAyYXhIQ',
    appId: '1:305013485493:android:04a22d64592daf118233fc',
    messagingSenderId: '305013485493',
    projectId: 'lazez-32651',
    databaseURL: 'https://lazez-32651-default-rtdb.firebaseio.com',
    storageBucket: 'lazez-32651.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUS72Z3P47G1YCNWTu_hJV6LRFzHwKzvE',
    appId: '1:305013485493:ios:313d1f7c17282cf68233fc',
    messagingSenderId: '305013485493',
    projectId: 'lazez-32651',
    databaseURL: 'https://lazez-32651-default-rtdb.firebaseio.com',
    storageBucket: 'lazez-32651.firebasestorage.app',
    androidClientId: '305013485493-9eitd2lijs10o5j4928f5gt63ioor0fu.apps.googleusercontent.com',
    iosClientId: '305013485493-lri06osk6k0jpl5idosb2kcvnitj24u6.apps.googleusercontent.com',
    iosBundleId: 'com.lazeez.driver.ios',
  );

}